name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize and apply Terraform
        run: |
          cd .terraform
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Build project
        run: ./gradlew clean build

      - name: Copy jar to EC2
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem build/libs/nasaws-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.HOST_DNS }}:/home/ec2-user/app.jar
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Run app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.HOST_DNS }} << 'EOF'
            export NASA_API_KEY=$(aws secretsmanager get-secret-value --secret-id nasa_api_key --query SecretString --output text | jq -r '.NASA_API_KEY')
            pkill -f 'java -jar' || true
            nohup java -jar app.jar > app.log 2>&1 &
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}